server:
  port: 9092

spring:
  application:
    name: QUESTION-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/ms_project
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/